modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0"

[[mods]]
modId="areamonitor"
version="2.0.5"
displayName="Area Monitor"
authors="Kavinshi"
displayURL="https://github.com/kavin-shi-source/AreaMonitor-Mod-1.20.1-forge"
logoFile="icon.png"
description='''
Area Monitor - Monitor player areas and automatically switch game modes.
Supports multiple areas, whitelist, item blacklist, and multi-language.
'''

[[dependencies.areamonitor]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
